version: 1.0.{build}
skip_branch_with_pr: true
install:
  - cmd: appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/v3.5.0/NuGet.exe
before_build:
  - nuget restore Src/couchbase-net-linq.sln
build:
  verbosity: minimal
test:
  assemblies:
    - '**\bin\Debug\Couchbase.Linq.UnitTests.dll'
